name: test
description: Test framework for Toit, focusing on host-base unit tests.
environment:
  sdk: ^2.0.0-alpha.120
dependencies:
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.2.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.8.1
  tar:
    url: github.com/toitlang/pkg-tar
    version: ^1.0.0
